name: Check

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - .github/workflows/check.yml
      - fenster-dev-1.rockspec
      - 'src/**'

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/check.yml
      - fenster-dev-1.rockspec
      - 'src/**'

  workflow_dispatch:

jobs:
  test-build:
    name: Test Build

    strategy:
        matrix:
          os: [ ubuntu-latest, windows-latest ]
          lua_version: [ '5.1', '5.2', '5.3', '5.4', 'luajit' ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # This will be ignored on platforms other than Windows
      - name: Setup Microsoft Visual C++ Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10.0.0
        with:
          luaVersion: ${{ matrix.lua_version }}

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: Run luarocks build
        run: luarocks build

      - name: Run basic test
        run: lua -e "require('luarocks.loader');local fenster = require('fenster');print(fenster.time())"
