name: Check Clang

on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Lua
        uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10.0.0

      - name: Setup LuaRocks
        uses: hishamhm/gh-actions-luarocks@master

      - name: Run clang-format
        run: |
          # "notify" me of newer clang-format version
          if command -v clang-format-16 &> /dev/null; then
            echo "clang-format-16 is available"
            exit 2
          fi

          shopt -s nullglob
          files=(src/*.c src/*.h)
          if [[ "${#files[@]}" -eq 0 ]]; then
            echo "No files found"
            exit 1
          fi
          clang-format-15 --verbose --dry-run --Werror "${files[@]}"

      - name: Run clang-tidy
        run: |
          # "notify" me of newer clang-tidy version
          if command -v clang-tidy-16 &> /dev/null; then
            echo "clang-tidy-16 is available"
            exit 2
          fi
          
          shopt -s nullglob
          sources=(src/*.c src/*.h)
          if [[ "${#sources[@]}" -eq 0 ]]; then
            echo "No sources found"
            exit 1
          fi
          clang-tidy-15 --extra-arg="-I.lua/include" --warnings-as-errors="*" "${sources[@]}"
