name: TEMP Check

on:
  workflow_dispatch:

jobs:
  test-build:
    name: Test Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Microsoft Visual C++ Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10.0.0
        with:
          luaVersion: 5.4

      - name: Setup LuaRocks
        uses: hishamhm/gh-actions-luarocks@master

      - name: Run luarocks build
        run: luarocks build

      - name: Run a basic test
        run: lua -e "local fenster = require('fenster');print(fenster.time())"
